[plugins]
io-spring-dependency-management = { id = 'io.spring.dependency-management', version = '1.1.6' }
org-springframework-boot = { id = 'org.springframework.boot', version = '3.3.2' }

[versions]
aspectj = '1.9.22.1'
jackson = '2.17.2'
junit = '5.10.3'
mapstruct = '1.5.5.Final'

[libraries]
aspectj-rt = { module = 'org.aspectj:aspectjrt', version.ref = 'aspectj' }
aspectj-weaver = { module = 'org.aspectj:aspectjweaver', version.ref = 'aspectj' }
assertj = 'org.assertj:assertj-core:3.25.3'
commons-collections4 = 'org.apache.commons:commons-collections4:4.4'
commons-io = 'commons-io:commons-io:2.15.1'
commons-lang3 = 'org.apache.commons:commons-lang3:3.14.0'
guava = 'com.google.guava:guava:32.1.3-jre'
jackson-core = { module = 'com.fasterxml.jackson.core:jackson-core', version.ref = 'jackson' }
jackson-databind = { module = 'com.fasterxml.jackson.core:jackson-databind', version.ref = 'jackson' }
jackson-dataformat-yaml = { module = 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml', version.ref = 'jackson' }
jackson-datatype-jsr310 = { module = 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310', version.ref = 'jackson' }
jakarta-annotation-api = 'jakarta.annotation:jakarta.annotation-api:3.0.0'
jakarta-validation-api = 'jakarta.validation:jakarta.validation-api:3.0.2'
jaxb-api = 'javax.xml.bind:jaxb-api:2.4.0-b180830.0359'
jsonwebtoken = 'io.jsonwebtoken:jjwt:0.9.1'
junit-jupiter-api = { module = 'org.junit.jupiter:junit-jupiter-api', version.ref = 'junit' }
junit-jupiter-engine = { module = 'org.junit.jupiter:junit-jupiter-engine', version.ref = 'junit' }
keycloakbom = 'org.keycloak.bom:keycloak-adapter-bom:12.0.4'
log4j-log4j = 'log4j:log4j:1.2.17'
logback-classic = 'ch.qos.logback:logback-classic:1.5.6'
logback-core = 'ch.qos.logback:logback-core:1.5.6'
lombok = 'org.projectlombok:lombok:1.18.32'
mapstruct = { module = 'org.mapstruct:mapstruct', version.ref = 'mapstruct' }
mapstruct-processor = { module = 'org.mapstruct:mapstruct-processor', version.ref = 'mapstruct' }
openapi-api = 'org.springdoc:springdoc-openapi-starter-webmvc-api:2.6.0'
openapi-ui = 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'
slf4j-api = 'org.slf4j:slf4j-api:2.0.7'
slf4j-log4j12 = 'org.slf4j:slf4j-log4j12:2.0.13'
spring-cloud = 'org.springframework.cloud:spring-cloud-dependencies:2023.0.3'
