#
# Copyright 2020-2022 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#-----------------------------------------------------------------------------------------------------------------------
# Portable default values for use with spvitamin
#-----------------------------------------------------------------------------------------------------------------------

#-----------------------------------------------------------------------------------------------------------------------
# Spring settings
#-----------------------------------------------------------------------------------------------------------------------
spring:
  jackson:
    serialization.write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: ${system.time-zone}
  mvc.pathmatch.matching-strategy: ant_path_matcher
  jpa.open-in-view: false
  lifecycle.timeout-per-shutdown-phase: 5s

#-----------------------------------------------------------------------------------------------------------------------
# Server settings
#-----------------------------------------------------------------------------------------------------------------------
server:
  tomcat.mbeanregistry.enabled: true
  shutdown: graceful


#-----------------------------------------------------------------------------------------------------------------------
# Springdoc settings
#-----------------------------------------------------------------------------------------------------------------------
springdoc:
  swagger-ui:
    # the path must end with /swagger-ui
    path: /docs/swagger-ui
    filter: true
  api-docs:
    path: /docs


#-----------------------------------------------------------------------------------------------------------------------
# Management endpoints
#-----------------------------------------------------------------------------------------------------------------------
management:
  endpoint:
    refresh.enabled: true
    health:
      probes:
        enabled: true
      show-details: always
      group:
        startup:
          include: "ping, diskSpace"
        readiness:
          include: "ping, readinessState"
        liveness:
          include: "ping, livenessState"
    env:
      show-values: never
  endpoints:
    web.exposure.include: health,info,metrics,prometheus
  health:
    db.enabled: false
    ldap.enabled: false
    refresh.enabled: false


#-----------------------------------------------------------------------------------------------------------------------
# Security settings
#-----------------------------------------------------------------------------------------------------------------------
security:
  oauth2:
    well-known-endpoints:
      microsoft:
        authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
        token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
        jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
        user-info-uri: https://graph.microsoft.com/oidc/userinfo
        user-name-attribute-name: sub
      facebook:
        authorization-uri: https://www.facebook.com/v12.0/dialog/oauth
        token-uri: https://graph.facebook.com/v12.0/oauth/access_token
        user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
        user-name-attribute-name: id
