/*
 * Copyright 2020-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id 'java-library'
    id 'jacoco'
    id 'maven-publish'
    id 'signing'
}
apply from: '../gradle/common.gradle'

repositories {
    mavenCentral()
}


dependencies {
    // -----------------------------------------------------------------------------------------------------------------
    // Compile dependencies
    // -----------------------------------------------------------------------------------------------------------------
    implementation project(':spvitamin-core')

    // Lombok
    compileOnly libs.lombok
    testCompileOnly libs.lombok
    annotationProcessor libs.lombok
    testAnnotationProcessor libs.lombok

    // apache.commons
    implementation libs.commons.io
    implementation libs.commons.lang3
    implementation libs.commons.collections4

    // Jackson
    implementation libs.jackson.annotations
    implementation libs.jackson3.databind

    implementation libs.nv.i18n


    // -----------------------------------------------------------------------------------------------------------------
    // Test dependencies
    // -----------------------------------------------------------------------------------------------------------------
    // JUnit
    testImplementation libs.junit.jupiter.api
    testImplementation libs.junit.jupiter.engine
    testImplementation libs.junit.jupiter.params
    testImplementation libs.assertj
    testImplementation libs.awaitility
    testImplementation libs.guava
    testImplementation libs.jimfs
    testRuntimeOnly libs.junit.platform.launcher

    // Mockito
    testImplementation 'org.mockito:mockito-core:5.11.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.11.0'

    // Spring Test
    testImplementation 'org.springframework:spring-test:6.1.7'

    // Slf4J
    implementation libs.slf4j.api
    testImplementation libs.slf4j.log4j12
    testImplementation libs.log4j.log4j

    // Jackson
    testImplementation libs.jackson3.databind
}


test {
    useJUnitPlatform()
}
